// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTodo(arg1) {
  return window['go']['handler']['App']['CheckTodo'](arg1);
}

export function CreateTodo(arg1, arg2, arg3) {
  return window['go']['handler']['App']['CreateTodo'](arg1, arg2, arg3);
}

export function DeleteTodo(arg1) {
  return window['go']['handler']['App']['DeleteTodo'](arg1);
}

export function GetAllTodos() {
  return window['go']['handler']['App']['GetAllTodos']();
}

export function GetTodoByID(arg1) {
  return window['go']['handler']['App']['GetTodoByID'](arg1);
}

export function UpdateTodo(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['App']['UpdateTodo'](arg1, arg2, arg3, arg4);
}
