// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {domain} from '../models';

export function CheckTodo(arg1:string):Promise<void>;

export function CreateTodo(arg1:string,arg2:string,arg3:time.Time):Promise<domain.Todo>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GetAllTodos():Promise<Array<domain.Todo>>;

export function GetTodoByID(arg1:string):Promise<domain.Todo>;

export function UpdateTodo(arg1:string,arg2:string,arg3:string,arg4:time.Time):Promise<domain.Todo>;
